Repository yiisoft/app, pull requests merged in 2020-06, with the labels that each got.

#1 Initial commit
  .gitattributes
  .github/workflows/build.yml
  .gitignore
  .phan/config.php
  README.md
  codeception.yml
  composer.json
  config/common.php
  config/console.php
  config/events-console.php
  config/events-web.php
  config/events.php
  config/params.php
  config/providers-console.php
  config/providers-web.php
  config/providers.php
  config/routes.php
  config/web.php
  docs/images/home.png
  package.json
  public/.htaccess
  public/assets/.gitignore
  public/favicon.ico
  public/images/yii-logo.jpg
  public/index.php
  resources/assets/css/site.css
  resources/layout/_footer.php
  resources/layout/_head.php
  resources/layout/_menu.php
  resources/layout/main.php
  resources/views/site/index.php
  runtime/cache/.gitignore
  runtime/debug/.gitignore
  runtime/logs/.gitignore
  src/Asset/AppAsset.php
  src/Asset/BulmaAsset.php
  src/Controller/AbstractController.php
  src/Controller/SiteController.php
  src/LayoutParameters.php
  src/Provider/CacheProvider.php
  src/Provider/EventDispatcherProvider.php
  src/Provider/LoggerProvider.php
  src/Provider/MiddlewareProvider.php
  src/Provider/PSR17Provider.php
  src/Provider/RouterProvider.php
  src/Provider/WebViewProvider.php
  tests/_support/AcceptanceTester.php
  tests/_support/FunctionalTester.php
  tests/_support/Helper/Acceptance.php
  tests/_support/Helper/Functional.php
  tests/_support/Helper/Unit.php
  tests/_support/UnitTester.php
  tests/_support/_generated/.gitignore
  tests/acceptance.suite.yml
  tests/acceptance/IndexAcceptanceCest.php
  tests/functional.suite.yml
  tests/functional/.gitkeep
  tests/functional/IndexFunctionalCest.php
  tests/unit.suite.yml
  tests/unit/.gitkeep
Labels: status:code review

#3 Enhacements.
  .github/workflows/build.yml
  README.md
  config/console.php
  config/params.php
  config/providers.php
  config/web.php
  resources/layout/_menu.php
  src/ApplicationParameters.php
  src/Provider/CacheProvider.php
  src/Provider/FileRotatorProvider.php
  src/Provider/FileTargetProvider.php
  src/Provider/LoggerProvider.php
  src/Provider/Psr17Provider.php
  src/Provider/SessionProvider.php
Labels: status:code review

#5 Fix broken codepception phpunit ^9.2.0
  composer.json
Labels: status:code review

#4 Put test log to the runtime directory in example
  README.md
Labels: status:code review

#6 Fix default options ApplicationParameters::class.
  src/ApplicationParameters.php
Labels: status:code review

#7 Add support php 8.0
  .github/workflows/build.yml
Labels: status:code review

#8 Fix dependency c3.
  public/index.php
Labels: status:code review

#12 Remove ignoring composer.lock.
  .gitignore
Labels: status:code review

#13 Simplify layout
  README.md
  config/params.php
  config/web.php
  resources/layout/_footer.php
  resources/layout/_head.php
  resources/layout/_menu.php
  resources/layout/main.php
  src/ApplicationParameters.php
Labels: status:code review, type:enhancement

#14 Enhacements.
  README.md
  composer.json
  config/params.php
  config/providers.php
  src/Provider/CacheProvider.php
  src/Provider/FileRotatorProvider.php
  src/Provider/LoggerProvider.php
  src/Provider/SessionProvider.php
  src/Provider/WebViewProvider.php
Labels: status:code review

#17 Separate web providers
  config/providers-web.php
  config/providers.php
Labels: status:code review

#18 Enhacement home page.
  docs/images/home.png
  resources/layout/_footer.php
  resources/layout/main.php
  resources/views/site/index.php
  src/Asset/CdnFontAwesomeAsset.php
Labels: status:code review

#21 Improve controller name definition
  src/Controller/AbstractController.php
  src/Controller/SiteController.php
Labels: status:code review

#20 Enhacement pages.
  composer.json
  config/common.php
  config/params.php
  config/providers-web.php
  config/routes.php
  resources/assets/css/site.css
  resources/layout/_menu.php
  resources/layout/main.php
  resources/mail/contact.php
  resources/mail/layouts/html.php
  resources/views/site/about.php
  resources/views/site/contact.php
  src/ApplicationParameters.php
  src/Asset/AppAsset.php
  src/Asset/BulmaAsset.php
  src/Controller/AbstractController.php
  src/Controller/SiteController.php
  src/Form/ContactForm.php
  src/Provider/FieldProvider.php
  src/Provider/FlashProvider.php
  src/Provider/MailerInterfaceProvider.php
  src/Provider/SwiftSmtpTransportProvider.php
  src/Provider/SwiftTransportProvider.php
  src/Provider/WebViewProvider.php
  src/Service/Mailer.php
  src/Service/Message.php
  src/Widget/FlashMessage.php
  tests/acceptance/AboutCest.php
  tests/acceptance/ContactCest.php
  tests/acceptance/IndexCest.php
  tests/functional/ContactFormCest.php
  tests/functional/IndexFunctionalCest.php
Labels: status:under development
